spring.datasource.hikari.data-source-properties."[v$session.osuser]"=${RDAC_OSUSER}

# Primary Database Configuration
spring.datasource.primary.url = ${DATABASE_URL}
spring.datasource.primary.username = ${DATABASE_USERNAME}
spring.datasource.primary.password = ${DATABASE_PASSWORD}
spring.datasource.primary.driver-class-name=oracle.jdbc.OracleDriver

# Secondary Database Configuration
#spring.datasource.secondary.url=${SECONDARY_DATABASE_URL}
#spring.datasource.secondary.username=${SECONDARY_DATABASE_USERNAME}
#spring.datasource.secondary.password=${SECONDARY_DATABASE_PASSWORD}
#spring.datasource.secondary.driver-class-name=oracle.jdbc.OracleDriver

spring.mvc.dispatch-options-request=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#debug=true
