spring.datasource.hikari.data-source-properties."[v$session.osuser]"=${RDAC_OSUSER}

# Primary Database Configuration
spring.datasource.primary.url = ${DATABASE_URL}
spring.datasource.primary.username = ${DATABASE_USERNAME}
spring.datasource.primary.password = ${DATABASE_PASSWORD}
spring.datasource.primary.driver-class-name=oracle.jdbc.OracleDriver

# Secondary Database Configuration
spring.datasource.secondary.url=${STG_DATABASE_URL}
spring.datasource.secondary.username=${STG_DATABASE_USERNAME}
spring.datasource.secondary.password=${STG_DATABASE_PASSWORD}
spring.datasource.secondary.driver-class-name=oracle.jdbc.OracleDriver

spring.mvc.dispatch-options-request=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#MongoDB configuration

JAVA_OPTS=-Xmx2G

#spring.data.mongodb.uri=mongodb://myUser:myPassword@localhost:27017/mydatabase
spring.data.mongodb.uri=mongodb+srv://opllt_ro:Oplltro_420@mgdb-oplts1.cisco.com/opldb?retryWrites=false&loadBalanced=false&readPreference=secondary&srvServiceName=mongodb&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1


#debug=true
