standard.ar.exc.query = ${STANDARD_AR_EXC_QUERY}
tsv.topsku.exc.query = ${TSV_TOP_SKU_EXC_QUERY}
tsv.subsku.exc.query = ${TSV_SUB_SKU_EXC_QUERY}
# revenue.controls.query = ${REVENUE_CONTROLS_QUERY}
# period.close.invoice.stats = ${PERIOD_CLOSE_INVOICE_STATS}
# period.close.interface.load.preclose = ${PERIOD_CLOSE_INTERFACE_LOAD_PRECLOSE}
revenue.controls.q = ${REVENUE_CONTROLS_Q}
start-end.time.q = ${CLOSE_START_END_TIME_Q}
volume.q = ${CLOSE_VOLUME_Q}
me.status.q = ${CLOSE_ME_STATUS_Q}
inv.stats.q = ${CLOSE_INVOICE_STATS_Q}
interface.load.q = ${CLOSE_INTERFACE_LOAD_Q}
qe.cash.collected.q = ${CLOSE_QE_CASH_COLLECTED_Q}
dashboard.comments.q = ${ASK_QE_ME_DASH_BOARD_STATUS_Q}
update.comments.q = ${UPDATE_COMMENTS_Q}
error.summary.q = ${ERROR_SUMMARY_Q}
error.details.all.q=${ERROR_DETAILS_ALL_Q}
error.details.q = ${ERROR_DETAILS_Q}
order.status.q = ${ORDER_STATUS_Q}
wd0.ar.midclose.status.query = ${WD0_AR_MIDCLOSE_STATUS_QUERY}
wd0.ar.midclose.header.data.query = ${WD0_AR_MIDCLOSE_HEADER_DATA_QUERY}
wd0.historical.data.q = ${WD0_HISTORICAL_DATA_Q}
invoice.tracker.header.q = ${INVOICE_TRACKER_HEADER_QUERY}
invoice.tracker.line.q = ${INVOICE_TRACKER_LINE_QUERY}
update.order.status.q = ${UPDATE_ORDER_STATUS_Q}
order.status.summary.q = ${ORDER_STATUS_SUMMARY_Q}
order.status.download.q = ${ORDER_STATUS_DOWNLOAD_Q}
kafka.error.q = ${KAFKA_ERROR_QUERY}
kafka.inbound.q = ${KAFKA_INBOUND_QUERY}
ar.trxn.missing.q = ${AR_TRXN_MISSING_QUERY}
accruals.processing.errors.q = ${ACCRUALS_PROCESSING_ERRORS_QUERY}
accruals.distribution.errors.q = ${ACCRUALS_DISTRIBUTION_ERRORS_QUERY}
accruals.summarization.errors.q = ${ACCRUALS_SUMMARIZATION_ERRORS_QUERY}
kafka.publish.to.downstream.q = ${KAFKA_PUBLISH_TO_DOWNSTREAM_QUERY}
error.distribution.summarization.q = ${ERRORS_DISTRIBUTION_SUMMARIZATION_QUERY}
