standard.ar.exc.query = ${STANDARD_AR_EXC_QUERY}
tsv.topsku.exc.query = ${TSV_TOP_SKU_EXC_QUERY}
tsv.subsku.exc.query = ${TSV_SUB_SKU_EXC_QUERY}
# revenue.controls.query = ${REVENUE_CONTROLS_QUERY}
# period.close.invoice.stats = ${PERIOD_CLOSE_INVOICE_STATS}
# period.close.interface.load.preclose = ${PERIOD_CLOSE_INTERFACE_LOAD_PRECLOSE}
revenue.controls.q = ${REVENUE_CONTROLS_Q}
start-end.time.q = ${CLOSE_START_END_TIME_Q}
volume.q = ${CLOSE_VOLUME_Q}
me.status.q = ${CLOSE_ME_STATUS_Q}
inv.stats.q = ${CLOSE_INVOICE_STATS_Q}
interface.load.q = ${CLOSE_INTERFACE_LOAD_Q}
qe.cash.collected.q = ${CLOSE_QE_CASH_COLLECTED_Q}
dashboard.comments.q = ${ASK_QE_ME_DASH_BOARD_STATUS_Q}
update.comments.q = ${UPDATE_COMMENTS_Q}
error.summary.q = ${ERROR_SUMMARY_Q}
error.details.all.q=${ERROR_DETAILS_ALL_Q}
error.details.q = ${ERROR_DETAILS_Q}
order.status.q = ${ORDER_STATUS_Q}
wd0.ar.midclose.status.query = ${WD0_AR_MIDCLOSE_STATUS_QUERY}
wd0.ar.midclose.header.data.query = ${WD0_AR_MIDCLOSE_HEADER_DATA_QUERY}
wd0.historical.data.q = ${WD0_HISTORICAL_DATA_Q}
invoice.tracker.header.q = ${INVOICE_TRACKER_HEADER_QUERY}
invoice.tracker.line.q = ${INVOICE_TRACKER_LINE_QUERY}
update.order.status.q = ${UPDATE_ORDER_STATUS_Q}
order.status.summary.q = ${ORDER_STATUS_SUMMARY_Q}
order.status.download.q = ${ORDER_STATUS_DOWNLOAD_Q}
kafka.error.q = ${KAFKA_ERROR_QUERY}
kafka.inbound.q = ${KAFKA_INBOUND_QUERY}
ar.trxn.missing.q = ${AR_TRXN_MISSING_QUERY}
accruals.processing.errors.q = ${ACCRUALS_PROCESSING_ERRORS_QUERY}
accruals.distribution.errors.q = ${ACCRUALS_DISTRIBUTION_ERRORS_QUERY}
accruals.summarization.errors.q = ${ACCRUALS_SUMMARIZATION_ERRORS_QUERY}
kafka.publish.to.downstream.q = ${KAFKA_PUBLISH_TO_DOWNSTREAM_QUERY}
error.distribution.summarization.q = ${ERRORS_DISTRIBUTION_SUMMARIZATION_QUERY}
order.status.rev.summary.q = ${ORDER_STATUS_REV_SUMMARY_Q}
persona.access.q = ${PERSONA_ACCESS_QUERY}
wd0.regression.q = ${WD0_REGRESSION_QUERY}
wd0.current.month.q = ${WDO_CURRENT_MONTH_QUERY}
delete.selected.deals.q=${DELETE_SELECTED_DEALS_QUERY}
clo.bulk.update.q=${CLO_BULK_UPDATE_QUERY}
invoice.eligible.update.q=${INVOICE_ELIGIBLE_DATE_UPDATE_QUERY}
clo.comment.update.q=${CLO_COMMENTS_UPDATE_QUERY}
cms.unposted.summary.query = ${CMS_UNPOSTED_SUMMARY_QUERY}
cms.receipt.error.summary = ${CMS_RECEIPT_ERROR_SUMMARY_QUERY}
cms.ctm.status.query = ${CMS_CTM_STATUS_QUERY}
cms.ctm.details.query = ${CMS_CTM_DETAILS_QUERY}
cms.boomi.status.query = ${CMS_BOOMI_STATUS_QUERY}
cms.boomi.details.query= ${CMS_BOOMI_DETAILS_QUERY}
cms.extract.count.query=${CMS_EXTRACT_COUNT_QUERY}
cms.extract.details.query=${CMS_EXTRACT_DETAILS_QUERY}
cms.latest.request.status.query=${CMS_LATEST_REQUEST_STATUS_QUERY}
cms.collections.error.summary.query=${CMS_COLLECTIONS_ERROR_SUMMARY_QUERY}
cms.invoice.pdf.extract.error.query=${CMS_INVOICE_PDF_EXTRACT_ERR_QUERY}
cms.invoice.extract.error.query=${CMS_INVOICE_EXTRACT_ERR_QUERY}
cms.customer.master.error.query=${CMS_CUSTOMER_MASTER_ERR_QUERY}
cms.alternate.payer.error.query=${CMS_ALTERNATE_PAYER_ERR_QUERY}
cms.sales.invoice.header.extract.error.query=${CMS_SALES_INVOICE_HEADER_EXTRACT_ERR_QUERY}
cms.customer.contacts.error.query=${CMS_CUSTOMER_CONTACTS_ERR_QUERY}
cms.sales.invoice.item.extract.query=${CMS_SALES_INVOICE_ITEM_EXTRACT_ERR_QUERY}
cms.interface.errors.query=${CMS_INTERFACE_ERRORS_QUERY}
cms.interface.error.count.in.xhrs.query=${CMS_INTERFACE_ERROR_COUNT_IN_XHRS_QUERY}
cms.unposted.total.amount.query=${CMS_UNPOSTED_TOTAL_AMOUNT_QUERY}
cms.total.reconciliation.error.query=${CMS_TOTAL_RECONCILIATION_ERROR_QUERY}
cms.boomi.status.hr.to.cg1.query=${CMS_BOOMI_STATUS_HR_TO_CG1_QUERY}
cms.boomi.details.hr.to.cg1.query=${CMS_BOOMI_DETAILS_HR_TO_CG1_QUERY}
cms.core.app.layer.error.count.query=${CMS_CORE_APP_LAYER_ERROR_COUNT_QUERY}
cms.recon.err.count.extract.query=${CMS_RECON_ERR_COUNT_EXTRACT_QUERY}
rol.transaction.data.query=${ROL_TRANSACTION_DATA_QUERY}
rol.transaction.data.filter.query=${ROL_TRANSACTION_DATA_FILTER_QUERY}
rol.transaction.data.filter.count.query=${ROL_TRANSACTION_DATA_FILTER_COUNT_QUERY}
rol.transaction.data.count.query=${ROL_TRANSACTION_DATA_COUNT_QUERY}
rol.errors.summary.query=${ROL_ERRORS_SUMMARY_QUERY}
rol.errors.summary.update.query=${ROL_ERRORS_SUMMARY_UPDATE_QUERY}
rol.errors.summary.period.status.query=${ROL_ERRORS_SUMMARY_PERIOD_STATUS_QUERY}
rol.chart.totals.q = ${ROL_CHART_TOTALS_QUERY}
rol.chart.details.q = ${ROL_CHART_DETAILS_QUERY}
rol.transaction.data.download.q = ${ROL_TRANSACTION_DATA_DOWNLOAD_QUERY}
rol.transaction.filter.data.download.q = ${ROL_TRANSACTION_FILTER_DATA_DOWNLOAD_QUERY}
sbp.summary.query=${SBP_SUMMARY_QUERY}
sbp.details.q=${SBP_DETAILS_QUERY}
cms.total.unapplied.amount.query=${CMS_TOTAL_UNAPPLIED_AMOUNT_QUERY}
estimated.completion.time.query=${ESTIMATED_COMPLETION_TIME_QUERY}
large.deal.summary.by.account.query=${LARGE_DEAL_SUMMARY_BY_ACCOUNT_QUERY}
clo.sample.download.data.query=${CLO_SAMPLE_DOWNLOAD_DATA_QUERY}
case.service.metrics.summary=${CASE_SERVICE_METRICS_SUMMARY_QUERY}
wd0.volumes.q = ${WD0_VOLUMES_QUERY}
auto.invoice.error.summary.view.query=${AUTO_INVOICE_ERROR_SUMMARY_VIEW_QUERY}
auto.invoice.error.details.query=${AUTO_INVOICE_ERROR_DETAILS_QUERY}
auto.invoice.error.details.filtered.query=${AUTO_INVOICE_ERROR_DETAILS_QUERY_FILTERED}
pre.invoice.error.summary.view.query=${PRE_INVOICE_ERROR_SUMMARY_VIEW_QUERY}
pre.invoice.error.details.query=${PRE_INVOICE_ERROR_DETAILS_QUERY}
pre.invoice.error.details.filtered.query=${PRE_INVOICE_ERROR_DETAILS_QUERY_FILTERED}
auto.invoice.errors.summary.update.query=${AUTO_INVOICE_ERROR_SUMMARY_UPDATE_QUERY}
pre.invoice.errors.summary.update.query=${PRE_INVOICE_ERROR_SUMMARY_UPDATE_QUERY}
summary.assignment.users.query = ${SUMMARY_ASSIGNMENT_USERS_QUERY}
accruals.summary.q = ${ACCRUALS_SUMMARY_QUERY}
accruals.details.q = ${ACCRUALS_DETAILS_QUERY}
invoice.to.cash.summary.q = ${INVOICE_TO_CASH_SUMMARY}
accruals.details.filtered = ${ACCRUALS_DETAILS_FILTERED_QUERY}
accruals.summary.update.q = ${ACCRUALS_SUMMARY_UPDATE_QUERY}
gl.error.summary.q = ${GL_ERROR_SUMMARY_QUERY}
gl.error.details.q = ${GL_ERROR_DETAILS_QUERY}
gl.posting.details.filtered.q= ${GL_POSTING_DETAILS_FILTERED_QUERY}
gl.posting.summary.update.q = ${GL_POSTING_SUMMARY_UPDATE_QUERY}
einvoicing.summary.q = ${EINVOICING_SUMMARY_QUERY}
einvoicing.details.q = ${EINVOICING_DETAILS_QUERY}



