-- ============================================================
-- SDLC Sprint Update Tables — DDL + Seed Data
-- ============================================================

-- ── Drop existing objects (safe — ignores errors if they don't exist) ──

BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARFINRO.SDLC_EXEC_DATA CASCADE CONSTRAINTS';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARFINRO.SDLC_EXEC_VERSION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ARFINRO.SDLC_EXEC_DATA_SEQ';                 EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ARFINRO.SDLC_EXEC_VERSION_SEQ';              EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARFINRO.SDLC_ADOPT_DATA CASCADE CONSTRAINTS';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ARFINRO.SDLC_ADOPT_VERSION CASCADE CONSTRAINTS';EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ARFINRO.SDLC_ADOPT_DATA_SEQ';                EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ARFINRO.SDLC_ADOPT_VERSION_SEQ';             EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ── Table 1: SDLC Execution Update ──

CREATE SEQUENCE ARFINRO.SDLC_EXEC_VERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ARFINRO.SDLC_EXEC_DATA_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE ARFINRO.SDLC_EXEC_VERSION (
    VERSION_ID  NUMBER        DEFAULT ARFINRO.SDLC_EXEC_VERSION_SEQ.NEXTVAL PRIMARY KEY,
    SPRINT_NAME VARCHAR2(200) NOT NULL,
    CREATED_BY  VARCHAR2(100) NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    NOTES       VARCHAR2(500)
);

CREATE TABLE ARFINRO.SDLC_EXEC_DATA (
    DATA_ID      NUMBER        DEFAULT ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL PRIMARY KEY,
    VERSION_ID   NUMBER        NOT NULL REFERENCES ARFINRO.SDLC_EXEC_VERSION(VERSION_ID),
    WORKSTREAM   VARCHAR2(200) NOT NULL,
    COMPONENT    VARCHAR2(500),
    SCOPE        VARCHAR2(2000),
    SPRINT_UPDATE VARCHAR2(2000),
    STATUS       VARCHAR2(50)  DEFAULT 'YET_TO_START',
    SORT_ORDER   NUMBER        DEFAULT 0
);


-- ── Table 2: SDLC Component Adoption ──

CREATE SEQUENCE ARFINRO.SDLC_ADOPT_VERSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ARFINRO.SDLC_ADOPT_DATA_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE ARFINRO.SDLC_ADOPT_VERSION (
    VERSION_ID  NUMBER        DEFAULT ARFINRO.SDLC_ADOPT_VERSION_SEQ.NEXTVAL PRIMARY KEY,
    SPRINT_NAME VARCHAR2(200) NOT NULL,
    CREATED_BY  VARCHAR2(100) NOT NULL,
    CREATED_AT  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    NOTES       VARCHAR2(500)
);

CREATE TABLE ARFINRO.SDLC_ADOPT_DATA (
    DATA_ID      NUMBER        DEFAULT ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL PRIMARY KEY,
    VERSION_ID   NUMBER        NOT NULL REFERENCES ARFINRO.SDLC_ADOPT_VERSION(VERSION_ID),
    WORKSTREAM   VARCHAR2(200) NOT NULL,
    COMPONENT    VARCHAR2(500) NOT NULL,
    PM_STATUS    VARCHAR2(50)  DEFAULT 'NA',
    PM_PCT       VARCHAR2(20),
    OM_STATUS    VARCHAR2(50)  DEFAULT 'NA',
    OM_PCT       VARCHAR2(20),
    SM_STATUS    VARCHAR2(50)  DEFAULT 'NA',
    SM_PCT       VARCHAR2(20),
    I2C_STATUS   VARCHAR2(50)  DEFAULT 'NA',
    I2C_PCT      VARCHAR2(20),
    P2P_STATUS   VARCHAR2(50)  DEFAULT 'NA',
    P2P_PCT      VARCHAR2(20),
    FPP_STATUS   VARCHAR2(50)  DEFAULT 'NA',
    FPP_PCT      VARCHAR2(20),
    AIT_STATUS   VARCHAR2(50)  DEFAULT 'NA',
    AIT_PCT      VARCHAR2(20),
    CAPITAL_STATUS VARCHAR2(50) DEFAULT 'NA',
    CAPITAL_PCT  VARCHAR2(20),
    SORT_ORDER   NUMBER        DEFAULT 0
);


-- ============================================================
-- Seed Data: S15 (Sprint 15)
-- ============================================================

-- S15 Execution Update
INSERT INTO ARFINRO.SDLC_EXEC_VERSION (VERSION_ID, SPRINT_NAME, CREATED_BY, NOTES)
  VALUES (ARFINRO.SDLC_EXEC_VERSION_SEQ.NEXTVAL, 'S15', 'jasloop', 'Initial seed — Sprint 15');

-- Foundation
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Foundation (Partnering w/FTO, Capital & GTC PMO)', '', 'Establish FinIQ baseline for O2C, Accounting, P2P and Capital components', 'Starting Mar 9th, FinIQ metrics will be published on completeness of business & IT content / documents loaded. Every SDLC milestone will iterate / contribute to FinIQ (Due S17)', 'ON_WATCH', 1);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Foundation (Partnering w/FTO, Capital & GTC PMO)', '', 'Reverse engineer codebase to power FinIQ content (CodeReef) (PILOT)', 'CodeReef pilot (Revenue Accruals) to generate product feature description completed; iterations in progress', 'ON_WATCH', 2);

-- Requirements Authoring and Validation
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Requirements Authoring and Validation (Partnering w/FTO, Capital & GTC PMO)', '', 'Pilot FinIQ for Business Requirements authoring (PILOT)', 'Initiated Requirement Authoring Agent for Germany e-Invoicing and ICMS blind discount automation as Pilot use cases.', 'ON_TRACK', 3);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Requirements Authoring and Validation (Partnering w/FTO, Capital & GTC PMO)', '', 'New Offers, Buying Programs, PCM, Renewals, Acquisitions, SOX & Accounting Questionnaires are complete, reviewed and approved', 'Finance Product Management to review and sign-off on Buying Programs and Country Enablement', 'ON_TRACK', 4);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Requirements Authoring and Validation (Partnering w/FTO, Capital & GTC PMO)', '', 'Commerce, Buying Program and Market access (QATAR) epics validated through PRIMA', '23 of 26 (88%) capabilities for May/Jun releases will be validated through PRIMA', 'ON_TRACK', 5);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Requirements Authoring and Validation (Partnering w/FTO, Capital & GTC PMO)', '', 'PRIMA to capture questionnaire quality (NEW)', 'PRIMA capability to publish metrics on epics and capabilities validated (Due TBD)', 'ON_TRACK', 6);

-- Solution Design
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Solution Design', '', 'Order-to-Cash components generate solution design through AnA for May & June releases', '15 of 24 (62%) capabilities for May/Jun releases will leverage AnA agent for solution design generation', 'ON_TRACK', 7);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Solution Design', '', 'AnA to capture analyst feedback to measure its quality (NEW)', 'Survey questionnaire created to capture analyst feedback on AnA agent quality (Due TBD)', 'ON_TRACK', 8);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Solution Design', '', 'Integrate AnA with Product Catalog for effective generation of Jira features and User stories to be consumed during testing (PILOT)', 'Jira feature and user stories for Revenue Accruals leveraged for Test scenario preparation', 'ON_TRACK', 9);

-- Build
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Build', '', '80% adoption for Shredder (SAST scans) and Dependabot (outdated libraries)', '99% engineers enabled Shredder plugins; 93% repos enabled with Dependabot', 'ON_TRACK', 10);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Build', '', 'Code changes are hardgated through SonarQube (code quality and coverage)', 'Non-Oracle code hardgating in place; Oracle code will be in place in May/Jun', 'ON_WATCH', 11);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Build', '', 'Technical Design Agent framework (NEW)', '', 'YET_TO_START', 12);

-- Test
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Test', '', '100% adoption of Test platform readiness to avoid environment-related defects', 'Environmental defects reduced by 33% since implementation of the automation framework.', 'ON_TRACK', 13);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Test', '', '100% Regression Automation in O2C, Entity enablement in Accounting, and Capital APJC', 'Automation efforts to be completed for 44/72 O2C product features by Q3FY26', 'ON_TRACK', 14);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Test', '', 'Development of Autonomous Testing Agents using AnA-generated features and User stories (Test Planning, Data Creation, and Test Execution) (NEW)', 'Leverage Zephyr for Product Catalog and Test Case Repo creation', 'ON_TRACK', 15);

-- Production Support
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Production Support', '', '100% availability of all resolution agents for service requests related issues', '73/80 resolution agents deployed for CaseIQ (Dashboard available March 4th)', 'ON_TRACK', 16);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Production Support', '', 'CaseIQ to recommend route out and cancelled cases', 'CaseIQ enhanced to recommend routed out and cancelled cases; Demo scheduled for Mar 5th', 'ON_TRACK', 17);
INSERT INTO ARFINRO.SDLC_EXEC_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, SCOPE, SPRINT_UPDATE, STATUS, SORT_ORDER)
  VALUES (ARFINRO.SDLC_EXEC_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_EXEC_VERSION_SEQ.CURRVAL, 'Production Support', '', 'CaseIQ to reopen cases for which resolution is not accepted by requestor (NEW)', '', 'YET_TO_START', 18);

-- S15 Component Adoption
INSERT INTO ARFINRO.SDLC_ADOPT_VERSION (VERSION_ID, SPRINT_NAME, CREATED_BY, NOTES)
  VALUES (ARFINRO.SDLC_ADOPT_VERSION_SEQ.NEXTVAL, 'S15', 'jasloop', 'Initial seed — Sprint 15');

-- Foundation / Knowledge Hub
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Foundation / Knowledge Hub', 'FinIQ Content (Business Process Flows, Solution Documents, Technical Design, Architecture Diagrams, Product Catalog)', 'ON_WATCH', '90%', 'ON_WATCH', '80%', 'ON_WATCH', '80%', 'ON_WATCH', '80%', 'ON_WATCH', '90%', 'ON_WATCH', '80%', 'ON_WATCH', '', 'ON_WATCH', '80%', 1);

-- Requirements Authoring & Validation
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Requirements Authoring & Validation', 'Authoring Agent (Germany eInvoicing & ICMS Blind Discounts)', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 2);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Requirements Authoring & Validation', 'PRIMA', 'YET_TO_START', '', 'NA', '', 'NA', '', 'NA', '', 'NA', '', 'NA', '', 'NA', '', 'NA', '', 3);

-- Solution Design
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Solution Design', 'AnA', 'NA', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'YET_TO_START', '', 4);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Solution Design', 'Product Catalog Features', 'NA', '', 'ON_WATCH', '', 'ON_WATCH', '', 'ON_WATCH', '', 'ON_WATCH', '', 'ON_WATCH', '', 'ON_WATCH', '', 'YET_TO_START', '', 5);

-- Build
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Build', 'CoPilot', 'NA', '', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 6);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Build', 'Shredder', 'NA', '', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '96%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 7);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Build', 'Dependabot', 'NA', '', 'ON_TRACK', '99%', 'ON_TRACK', '93%', 'ON_TRACK', '99%', 'ON_TRACK', '92%', 'ON_TRACK', '96%', 'ON_WATCH', '77%', 'ON_TRACK', '96%', 8);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Build', 'UtPLSQL', 'NA', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 9);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Build', 'CODA', 'NA', '', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 'ON_TRACK', '100%', 10);

-- Test
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Test', 'Test Environment Validation', 'NA', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 11);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Test', 'Regression Automation', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_WATCH', '', 12);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Test', 'Test Agent', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 13);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Test', 'Fluent', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 14);

-- Production Support
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Production Support', 'Resolution Agent', 'NA', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 'ON_TRACK', '', 15);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Production Support', 'Routed out Recommendation', 'NA', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 16);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Production Support', 'Cancelled case Recommendation', 'NA', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 17);
INSERT INTO ARFINRO.SDLC_ADOPT_DATA (DATA_ID, VERSION_ID, WORKSTREAM, COMPONENT, PM_STATUS, PM_PCT, OM_STATUS, OM_PCT, SM_STATUS, SM_PCT, I2C_STATUS, I2C_PCT, P2P_STATUS, P2P_PCT, FPP_STATUS, FPP_PCT, AIT_STATUS, AIT_PCT, CAPITAL_STATUS, CAPITAL_PCT, SORT_ORDER)
  VALUES (ARFINRO.SDLC_ADOPT_DATA_SEQ.NEXTVAL, ARFINRO.SDLC_ADOPT_VERSION_SEQ.CURRVAL, 'Production Support', 'Cases reopened by Users', 'NA', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 'YET_TO_START', '', 18);

COMMIT;
