cors.url = ${CORS_URL}
database.url.cg1 = ${DATABASE_URL}
database.username.cg1 = ${DATABASE_USERNAME}
database.password.cg1 = ${DATABASE_PASSWORD}
webex.url = ${WEBEX_URL}
webex.auth.token = ${AUTH_TOKEN}
webex.room.id = ${ROOM_ID}