schema = ${PACKAGE_SCHEMA}
catalog.name = ${DATABASE_PACKAGE}
cab.query = ${CAB_QUERY}
cab.query.page = ${CAB_QUERY_PAGE}
cab.details.query = ${CAB_DETAILS_QUERY}
daily.monitoring.query = ${DAILY_MONITORING_QUERY}