schema = ${PACKAGE_SCHEMA}
catalog.name = ${DATABASE_PACKAGE}
cab.query = ${CAB_QUERY}
cab.query.page = ${CAB_QUERY_PAGE}
cab.details.query = ${CAB_DETAILS_QUERY}
cab.update.query = ${CAB_UPDATE_QUERY}
daily.monitoring.query = ${DAILY_MONITORING_QUERY}
monitoring.details.query = ${MONITORING_DETAILS_QUERY}
last.run.query = ${LAST_RUN_QUERY}
exception.report.query = ${EXCEPTION_REPORT_QUERY}