import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-wd0-dash',
  templateUrl: './wd0-dash.component.html',
  styleUrls: ['./wd0-dash.component.css'],
})
export class Wd0DashComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}

  scrollToID(HTMLID: string): void {
    document.getElementById(HTMLID).scrollIntoView();
  }

  phase1DisplayedColumns: string[] = [
    'Entity',
    'Subprocess',
    'Gross Margin Impacting',
    'Expected Completion',
    'Actual Completion',
    'Status',
    '*Loaded into FCC',
  ];
  phase2DisplayedColumns: string[] = [
    'Process',
    'Description',
    'Subprocess',
    'Gross Margin Impacting',
    'Expected Duration (in mins)',
    'Actual Duration (in mins)',
    'Status',
    'Loaded into FCC',
  ];

  phase4DataSource = [
    {
      Process: 'Auto-elimination and consolidation',
      Description:
        'FCC Smart view refresh of auto elims, Final Gross Margin can be calculated at this time..',
      Subprocess: 'Consol to identify auto-elims to post and send to IT',
      'Gross Margin Impacting': 'Yes',
      'Expected Duration (in mins)': '40',
      'Actual Duration (in mins)': '26',
      Status: 'Completed',
      'Loaded into FCC': 'Yes',
    },
    {
      Process: '',
      Description:
        ' After data has been pushed into FCC, it is then loaded into the specific entities.',
      Subprocess: 'FCC Refresh - Entity Data Load into FCC',
      'Gross Margin Impacting': 'Yes',
      'Expected Duration (in mins)': '40',
      'Actual Duration (in mins)': '26',
      Status: 'Completed',
      'Loaded into FCC': 'Yes',
    },
    {
      Process: '',
      Description: '',
      Subprocess: 'FCC Consolidations ',
      'Gross Margin Impacting': 'Yes',
      'Expected Duration (in mins)': '40',
      'Actual Duration (in mins)': '26',
      Status: 'Completed',
      'Loaded into FCC': 'Yes',
    },
  ];

  phase3DataSource = [
    {
      Process: 'Data refresh in FCC and consolidation',
      Description:
        ' Starts within 10 mins from end of global VT run. This step is pushes data from CFN into FCC',
      Subprocess: 'FCC Refresh - Entities Data Push to FCC',
      'Gross Margin Impacting': 'Yes',
      'Expected Duration (in mins)': '40',
      'Actual Duration (in mins)': '26',
      Status: 'Completed',
      'Loaded into FCC': 'Yes',
    },
    {
      Process: '',
      Description:
        ' After data has been pushed into FCC, it is then loaded into the specific entities.',
      Subprocess: 'FCC Refresh - Entity Data Load into FCC',
      'Gross Margin Impacting': 'Yes',
      'Expected Duration (in mins)': '40',
      'Actual Duration (in mins)': '26',
      Status: 'Completed',
      'Loaded into FCC': 'Yes',
    },
    {
      Process: '',
      Description:
        'Once the data has been loaded, Phase 3 will finalize with the FCC consolidation',
      Subprocess: 'FCC Consolidations ',
      'Gross Margin Impacting': 'Yes',
      'Expected Duration (in mins)': '40',
      'Actual Duration (in mins)': '26',
      Status: 'Completed',
      'Loaded into FCC': 'Yes',
    },
  ];

  phase2DataSource = [
    {
      Process: 'VT entries processing',
      Description:
        'As VT runs, IC entries are posted, including IC Revenues and IC COGS.',
      Subprocess: 'Cisco Intercompany - Accounting & Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Duration (in mins)': 'NA',
      'Actual Duration (in mins)': '1:09',
      Status: 'Delayed',
      'Loaded into FCC': 'Yes',
    },
  ];

  phase1DataSource = [
    {
      Entity: 'India',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:09',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:42',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting (NGCCRM)',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Russia',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': 'NA',
      Status: 'NA',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': 'NA',
      Status: 'NA',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': 'NA',
      Status: 'NA',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: 'Brazil',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:55',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:56',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:56',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Mexico',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:05',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': 'NA',
      Status: 'NA',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': 'NA',
      Status: 'NA',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: 'China Panyu',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:57',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': 'NA',
      Status: 'NA',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: 'Australia',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:53',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'China',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:55',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Canada',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:04',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:40',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:40',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Japan',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:52',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Italy',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:53',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'South Africa',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:06',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'South Korea',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:54',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: 'Germany',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': 'NA',
      Status: 'NA',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: 'NL',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '0:57',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'UKH',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '1:33',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '2:47',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '2:49',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'US',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '6:10',
      Status: 'Completed',
      '*Loaded into FCC': 'NA',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': 'NA',
      'Actual Completion': '8:18',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': '9:25',
      'Actual Completion': '9:25',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
  ];
}
