import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-wd0-dash',
  templateUrl: './wd0-dash.component.html',
  styleUrls: ['./wd0-dash.component.css'],
})
export class Wd0DashComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}

  phase1DisplayedColumns: string[] = [
    'Entity',
    'Subprocess',
    'Gross Margin Impacting',
    //'Expected Completion',
    'Actual Completion',
    'Status',
    '*Loaded into FCC',
  ];

  phase1DataSource = [
    {
      Entity: 'India',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:09',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:42',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting (NGCCRM)',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    // {
    //   Entity: 'Russia',
    //   Subprocess: 'Invoicing',
    //   'Gross Margin Impacting': 'Yes',
    //    //'Expected Completion': 'N/A',
    //   'Actual Completion': 'N/A',
    //   Status: 'N/A',
    //   '*Loaded into FCC': 'N/A',
    // },
    // {
    //   Entity: '',
    //   Subprocess: 'Receivables Posting',
    //   'Gross Margin Impacting': 'Yes',
    //    //'Expected Completion': 'N/A',
    //   'Actual Completion': 'N/A',
    //   Status: 'N/A',
    //   '*Loaded into FCC': 'N/A',
    // },
    // {
    //   Entity: '',
    //   Subprocess: 'Revenue Posting',
    //   'Gross Margin Impacting': 'Yes',
    //    //'Expected Completion': 'N/A',
    //   'Actual Completion': 'N/A',
    //   Status: 'N/A',
    //   '*Loaded into FCC': 'N/A',
    // },
    {
      Entity: 'Brazil',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:55',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:56',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:56',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Mexico',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:05',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': 'N/A',
      Status: 'N/A',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': 'N/A',
      Status: 'N/A',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: 'ChiN/A Panyu',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:57',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': 'N/A',
      Status: 'N/A',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: 'Australia',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:53',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'ChiN/A',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:55',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'CaN/Ada',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:04',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:40',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:40',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Japan',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:52',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:27',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'Italy',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:53',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'South Africa',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:06',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'South Korea',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:54',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:50',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: 'Germany',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': 'N/A',
      Status: 'N/A',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: 'NL',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '0:57',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:34',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'UKH',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '1:33',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '2:47',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '2:49',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: 'US',
      Subprocess: 'Invoicing',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '6:10',
      Status: 'Completed',
      '*Loaded into FCC': 'N/A',
    },
    {
      Entity: '',
      Subprocess: 'Receivables Posting',
      'Gross Margin Impacting': 'Yes',
      //'Expected Completion': 'N/A',
      'Actual Completion': '8:18',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
    {
      Entity: '',
      Subprocess: 'Revenue Posting',
      'Gross Margin Impacting': 'Yes',
      'Expected Completion': '9:25',
      'Actual Completion': '9:25',
      Status: 'Completed',
      '*Loaded into FCC': 'Yes',
    },
  ];
}
