---
# Source: templates/dev.yaml

# codectl version : 1.5.2

apiVersion: v1
kind: Service
metadata:
  name: 'rev-accruals-backend-service'
  namespace: 'rev-accruals-monitoring-alln-nprd'
  labels:
    softwareId: '4c8aa5a11afc21fd32eb843f4f125c3e771d6816'
    softwareName: 'rev-accruals-monitoring'
spec:
  ports:
    - name: "server"
      protocol: "TCP"
      port: 8080
  selector:
      app: 'rev-accruals-monitoring-server'
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: 'rev-accruals-ui-service'
  namespace: 'rev-accruals-monitoring-alln-nprd'
  labels:
    softwareId: '4c8aa5a11afc21fd32eb843f4f125c3e771d6816'
    softwareName: 'rev-accruals-monitoring-ui'
spec:
  ports:
    - name: "ui"
      protocol: "TCP"
      port: 4200
  selector:
      app: 'rev-accruals-monitoring'
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'rev-accruals-monitoring-ui'
  namespace: 'rev-accruals-monitoring-alln-nprd'
  labels:
    softwareId: '4c8aa5a11afc21fd32eb843f4f125c3e771d6816'
    softwareName: 'rev-accruals-monitoring'
spec:
  selector:
    matchLabels:
      app: 'rev-accruals-monitoring-ui'
  replicas: 0
  template:
    metadata:
      namespace: 'rev-accruals-monitoring-alln-nprd'
      labels:
        app: 'rev-accruals-monitoring-ui'
        environment: 'dev'
        softwareId: '4c8aa5a11afc21fd32eb843f4f125c3e771d6816'
        softwareName: 'rev-accruals-monitoring'
    spec:
      containers:
      - image: 'containers.cisco.com/it_cvc_order_to_cash/rev-accruals-monitoring:ui-${trigger["parameters"]["imageTag"]}'
        imagePullPolicy: IfNotPresent
        name: 'rev-accruals-monitoring'
        ports:
        - containerPort: 4200
        volumeMounts:
            - name: env-config
              mountPath: /ui/app-root/src/assets/config
      imagePullSecrets:
      - name: it-cvc-order-to-cash-cdconsole-bot-pull-secret
      volumes:
        - configMap:
            name: environment-config
          name: env-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'rev-accruals-monitoring-server'
  namespace: 'rev-accruals-monitoring-alln-nprd'
  labels:
    softwareId: '4c8aa5a11afc21fd32eb843f4f125c3e771d6816'
    softwareName: 'rev-accruals-monitoring'
spec:
  selector:
    matchLabels:
      app: 'rev-accruals-monitoring-server'
  replicas: 1
  template:
    metadata:
      namespace: 'rev-accruals-monitoring-alln-nprd'
      labels:
        app: 'rev-accruals-monitoring-server'
        environment: 'dev'
        softwareId: '4c8aa5a11afc21fd32eb843f4f125c3e771d6816'
        softwareName: 'rev-accruals-monitoring'
    spec:
      containers:
      - name: 'rev-accruals-monitoring-server'
        env:
        - name: DATABASE_NAME
          valueFrom: 
            configMapKeyRef:
              key: db.name
              name: db-properties
        - name: DATABASE_URL
          valueFrom: 
            configMapKeyRef:
              key: db.url
              name: db-properties
        - name: CAB_QUERY
          valueFrom: 
            configMapKeyRef:
              key: cab.query
              name: db-properties
        - name: CAB_QUERY_PAGE
          valueFrom: 
            configMapKeyRef:
              key: cab.query.page
              name: db-properties
        - name: CAB_DETAILS_QUERY
          valueFrom: 
            configMapKeyRef:
              key: cab.details.query
              name: db-properties
        - name: CORS_URL
          valueFrom: 
            configMapKeyRef:
              key: cors.url
              name: server-properties
        - name: DATABASE_USERNAME
          valueFrom: 
            secretKeyRef:
              key: username
              name: db-credentials
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: password
              name: db-credentials
        - name: RDAC_OSUSER
          valueFrom: 
            secretKeyRef:
              key: osuser
              name: rdac
        image: 'containers.cisco.com/it_cvc_order_to_cash/rev-accruals-monitoring:server-${trigger["parameters"]["imageTag"]}'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: it-cvc-order-to-cash-cdconsole-bot-pull-secret

